---
name: Polycom-App-Push
version: 0.04
author: ["Zachary Blair <zblair@cpan.org>"]
abstract: 'Module for writing web applications for Polycom VoIP phones'
license: perl
distribution_type: module
resources:
  license: http://dev.perl.org/licenses/
configure_requires:
  ExtUtils::MakeMaker: 0
build_requires:
  ExtUtils::MakeMaker: 0
  Test::More: 0
requires:
  Class::Accessor: 0
  LWP::UserAgent: 0
  perl: 5.8
no_index:
  directory:
    - t
provides:
  Polycom::App::Push:
    file: lib/Polycom/App/Push.pm
    version: 0.04
  Polycom::App::URI:
    file: lib/Polycom/App/URI.pm
    version: 0.01
keywords:
  - Polycom
  - VoIP
  - App
  - Push
  - SoundPoint
  - VVX
  - CSV
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
